name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  set-up:
    name: set-up 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
    
      - name: Install dependencies
        run: make requirements
    
      - name: Run Dev-Setup
        run: make dev-setup

  run-tests:
    name:  run-tests
    runs-on: ubuntu-latest
    needs: set-up
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: make run-checks
  
  deploy-infrastructure:
    name: deploy-infrastructure
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up AWS credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
     
      - name: Terraform Init
        run: make terraform-init
      
      - name: Terraform Plan
        run: make terraform-plan
      
      - name: Terraform Apply
        run: make terraform-apply
  
  upload_data:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies for upload script
        run: make requirements
      
      - name: Upload Parquet file to S3
        env:
            
      


     
      
      
      
      
    
      
      




  upload_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        make requirements

    - name: Upload Parquet files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        make upload

    - name: Deploy Streamlit App
      run: |
        git push origin main
